swagger: "2.0"
info:
  description: "hello-api endpoints"
  title: "hello-api endpoints"
  version: "1.0.0"
host: hello-api.endpoints.samyn-project4.cloud.goog
x-google-endpoints:
  - name: "hello-api.endpoints.samyn-project4.cloud.goog"
security:
  - api_key: []
paths:
  /:
    get:
      summary: Version Page
      operationId: VersionPage
      produces:
        - application/json
      parameters: [ ]
      responses:
        200:
          description: ''
      security: []
  /healthz:
    get:
      summary: Health Page
      operationId: HealthPage
      produces:
        - application/text
      parameters: [ ]
      responses:
        200:
          description: ''
      security: []
  /secured:
    get:
      summary: Secured Page
      operationId: SecuredPage
      produces:
        - application/text
      parameters: [ ]
      responses:
        200:
          description: ''
  /notify/function1:
    post:
      summary: Notify Function1
      operationId: NotifyFunction1
      produces:
        - application/text
      parameters: [ ]
      responses:
        200:
          description: ''
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
