swagger: "2.0"
info:
  description: "hello-api endpoints"
  title: "hello-api endpoints"
  version: "1.0.0"
host: hello-api.endpoints.samyn-project4.cloud.goog
x-google-endpoints:
  - name: "hello-api.endpoints.samyn-project4.cloud.goog"
paths:
#  /:
#    get:
#      summary: Version Page
#      operationId: VersionPage
#      produces:
#        - application/json
#      parameters: [ ]
#      responses:
#        200:
#          description: ''
  /healthz:
    get:
      summary: Health Page
      operationId: HealthPage
      produces:
        - application/text
      parameters: [ ]
      responses:
        200:
          description: ''
