#!groovy

parameters([
    string(name: 'VERSION', defaultValue: 'dev', description: 'branch or tag', trim: true),
])

node {
    def repoURL     = 'git@github.com:dev2choiz/hello.git'
    def environment = "staging"
    def appTag      = params.VERSION

    echo "start building tag/branch '${appTag}'"
    stage("Checkout ${appTag}") {
        checkout scm: [
            $class           : 'GitSCM',
            userRemoteConfigs: [[url: repoURL]],
            branches         : [[name: appTag]]
        ], poll: false
    }

    def ws = pwd()
    def moduleVars = load "${ws}/deployments/jenkins/modules/variables.groovy"

    def commonSubst = [
        _APP_TAG: appTag,
        _GCP_REGION: moduleVars.gcpRegion,
    ]

    stage("Build image hello-front-next ${appTag}") {
        googleCloudBuild  \
        credentialsId: moduleVars.gcloudCredentialsId,
            source: local('.'),
            request: file('front-next/deployments/cloudbuild/build-image/cloudbuild.yaml'),
            substitutions: commonSubst + [
                _KMS_KEYRING_NAME: moduleVars.kmsKeyringName,
                _KMS_KEY_NAME: moduleVars.kmsKeyName,
            ]
    }

    stage("Deploy CloudRun ${appTag}") {
        googleCloudBuild  \
            credentialsId: moduleVars.gcloudCredentialsId,
            source: local('.'),
            request: file('front-next/deployments/cloudbuild/deploy-cloud-run/cloudbuild.yaml'),
            substitutions: commonSubst
    }
}
