version: '3.7'

services:
  esp:
    image: "gcr.io/endpoints-release/endpoints-runtime:2.29.1"
    depends_on:
      - hello
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/etc/nginx/creds/credentials.json
    command:
        - "--listener_port=9000"
        - "--backend=hello:8080"
        - "--service=hello-api.endpoints.samyn-project4.cloud.goog"
        - "--rollout_strategy=managed"
        - "--service_account_key=/etc/nginx/creds/credentials.json"
        - "--cors_preset=basic"
        - "--cors_allow_origin=http://localhost:8080"
        - "--non_gcp"
        - "--enable_debug"
        - "--ssl_server_cert_path=/etc/esp/ssl"
    ports:
      - 9000:9000
    volumes:
      - ./local/files/sa-hello-api-credentials.json:/etc/nginx/creds/credentials.json
      - ./local/files/cert/dev/certificate.crt:/etc/esp/ssl/server.crt
      - ./local/files/cert/dev/private.key:/etc/esp/ssl/server.key

  hello:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
      target: hello_api_dev
    command: bash -c "
      go mod vendor
      && go run main.go"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: '/volumes/secrets/sa/credentials.json'
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - ./volumes/empty-dir/:/volumes/empty-dir/
      - ./volumes/config-map/:/volumes/config-map/
      - ./volumes/secrets/:/volumes/secrets/fake-credentials/
      - ./local/files/sa-hello-api-credentials.json:/volumes/secrets/sa/credentials.json
      - ./volumes/go:/go
