version: '3.7'

services:
  primary:
    command: bash -c "
      go get github.com/go-delve/delve/cmd/dlv
      && cd cmd/apps/hello-api
      && dlv --listen=:2345 --headless=true --api-version=2 --accept-multiclient debug main.go"
    ports:
      - 2345:2345
