version: '3.7'

services:
  hello-api:
    command: bash -c "
      cd
      && go get github.com/go-delve/delve/cmd/dlv
      && cd -
      && dlv --listen=:2345 --headless=true --api-version=2 --accept-multiclient debug . -- hello-api --port=7080"
    ports:
      - 2345:2345
