version: '3.7'

services:
  esp:
    image: "gcr.io/endpoints-release/endpoints-runtime:2.29.1"
    depends_on:
      - hello-api
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/etc/nginx/creds/credentials.json
    command:
        - "--listener_port=9000"
        - "--backend=hello:8080"
        - "--service=hello-api.endpoints.samyn-project4.cloud.goog"
        - "--rollout_strategy=managed"
        - "--service_account_key=/etc/nginx/creds/credentials.json"
        - "--cors_preset=basic"
        - "--cors_allow_origin=http://localhost:8080"
        - "--non_gcp"
        - "--enable_debug"
        - "--ssl_server_cert_path=/etc/esp/ssl"
    ports:
      - 9000:9000
    volumes:
      - ./local/files/sa-hello-api-credentials.json:/etc/nginx/creds/credentials.json
      - ./local/files/cert/dev/certificate.crt:/etc/esp/ssl/server.crt
      - ./local/files/cert/dev/private.key:/etc/esp/ssl/server.key

  hello-api:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
      target: stage_dev
    command: bash -c "
      cd cmd/apps/hello-api
      && go run . -mode=grpc -grpc-port=7080 -http-port=8080"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: '/volumes/secrets/sa/credentials.json'
      SVC1_GRPC_BASE_URL: 'hello-svc1:7081'
      SVC2_GRPC_BASE_URL: 'hello-svc2:7082'
      SVC1_BASE_URL: 'http://hello-svc1:8081'
      SVC2_BASE_URL: 'http://hello-svc2:8082'
    ports:
      - '8080:8080'
      - '7080:7080'
    volumes:
      - .:/app
      - ./local/files/sa-hello-api-credentials.json:/volumes/secrets/sa/credentials.json
      - ./volumes/hello-api/go:/go

  hello-svc1:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
      target: stage_dev
    command: bash -c "
      cd cmd/apps/hello-svc
      && go run . -name=svc1 -mode=grpc -grpc-port=7081 -http-port=8081"
    ports:
      - '8081:8081'
      - '7081:7081'
    volumes:
      - .:/app
      - ./volumes/hello-svc1/go:/go

  hello-svc2:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
      target: stage_dev
    command: bash -c "
      cd cmd/apps/hello-svc
      && go run . -name=svc2 -mode=grpc -grpc-port=7082 -http-port=8082"
    ports:
      - '8082:8082'
      - '7082:7082'
    volumes:
      - .:/app
      - ./volumes/hello-svc2/go:/go

  protoc:
    build:
      context: .
      dockerfile: ./docker/protoc/Dockerfile
      target: release
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]
    volumes:
      - .:/app
