version: '3.7'

services:
  esp:
    image: "gcr.io/endpoints-release/endpoints-runtime:2"
    depends_on:
      - hello-api
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/etc/nginx/creds/credentials.json
    command:
        - "--listener_port=9000"
        - "--backend=grpc://hello-api:7080"
        - "--service=hello-api.endpoints.samyn-project4.cloud.goog"
        - "--rollout_strategy=managed"
        - "--service_account_key=/etc/nginx/creds/credentials.json"
        - "--cors_preset=basic"
        - "--cors_allow_headers=DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,OPTIONS,Host,User-Agent,Accept,Accept-Language,Accept-Encoding,Access-Control-Request-Method,Access-Control-Request-Headers,Referer,Origin,Connection,Sec-Fetch-Dest,Sec-Fetch-Mode,Sec-Fetch-Site,Pragma,Cache-Control,TE,x-grpc-web"
        #- "--cors_allow_origin=http://localhost:3000"
        #- "--cors_preset=cors_with_regex"
        #- "--cors_allow_origin_regex=*"
        - "--non_gcp"
        - "--enable_debug"
        - "--ssl_server_cert_path=/etc/esp/ssl"

    ports:
      - 9000:9000
    volumes:
      - ./local/files/sa-hello-api-credentials.json:/etc/nginx/creds/credentials.json
      - ./local/files/cert/dev/server.crt:/etc/esp/ssl/server.crt
      - ./local/files/cert/dev/server.key:/etc/esp/ssl/server.key

  hello-api:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
      target: stage_dev
    command: bash -c "
      cd cmd/apps/hello-api
      && go run . -port=7080"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: '/volumes/secrets/sa/credentials.json'
      SVC1_GRPC_BASE_URL: 'hello-svc1:7081'
      SVC2_GRPC_BASE_URL: 'hello-svc2:7082'
      SVC1_BASE_URL: 'http://hello-svc1:8081'
      SVC2_BASE_URL: 'http://hello-svc2:8082'
      APP_ENV: 'dev'
    ports:
      - '8080:8080'
      - '7080:7080'
    volumes:
      - .:/app
      - ./local/files/sa-hello-api-credentials.json:/volumes/secrets/sa/credentials.json
      - ./volumes/hello-api/go:/go

  hello-svc1:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
      target: stage_dev
    command: bash -c "
      cd cmd/apps/hello-svc
      && go run . -name=svc1 -port=7081"
    ports:
      - '8081:8081'
      - '7081:7081'
    environment:
      APP_ENV: 'dev'
    volumes:
      - .:/app
      - ./volumes/hello-svc1/go:/go

  hello-svc2:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
      target: stage_dev
    command: bash -c "
      cd cmd/apps/hello-svc
      && go run . -name=svc2 -port=7082"
    ports:
      - '8082:8082'
      - '7082:7082'
    environment:
      APP_ENV: 'dev'
    volumes:
      - .:/app
      - ./volumes/hello-svc2/go:/go

  protoc:
    build:
      context: .
      dockerfile: ./docker/images/protoc/Dockerfile
      target: release_dev
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]
    volumes:
      - .:/app
