#!groovy

parameters([
    string(name: 'VERSION', defaultValue: 'dev', description: 'branch or tag', trim: true),
])

node {
    def repoURL     = 'git@github.com:dev2choiz/hello.git'
    def environment = "staging"
    def appTag      = params.VERSION
    def commitShort = ""

    echo "start building tag/branch '${appTag}'"
    stage("Checkout ${appTag}") {
        checkout scm: [
            $class           : 'GitSCM',
            userRemoteConfigs: [[url: repoURL]],
            branches         : [[name: appTag]]
        ], poll: false
        commitShort = sh(script: 'git rev-parse HEAD', returnStdout: true).trim().substring(0, 7)
        echo "git commit: ${commitShort}"
    }

    def ws = pwd()
    def common = load "${ws}/deployments/jenkins/common.groovy"

    def commonSubst = [
        _APP_TAG: appTag,
    ]

    stage("Build image hello-front ${appTag}") {
        googleCloudBuild  \
        credentialsId: common.gcloudCredentialsId,
            source: local('.'),
            request: file('front/deployments/cloudbuild/build-image.yaml'),
            substitutions: commonSubst + []
    }

    stage("Deploy CloudRun ${appTag}") {
        googleCloudBuild  \
            credentialsId: common.gcloudCredentialsId,
            source: local('.'),
            request: file('front/deployments/cloudbuild/deploy-cloud-run.yaml'),
            substitutions: commonSubst + [
                _GCP_REGION  : common.gcpRegion,
            ]
    }
}
