#!groovy

parameters([
    string(name: 'VERSION', defaultValue: 'dev', description: 'branch or tag', trim: true),
])

node {

    def repoURL     = 'git@github.com:dev2choiz/hello.git'
    def appTag      = params.VERSION
    def commitShort = ""

    echo "start building tag/branch '${appTag}'"
    stage("Checkout ${appTag}") {
        checkout scm: [
            $class           : 'GitSCM',
            userRemoteConfigs: [[url: repoURL]],
            branches         : [[name: appTag]]
        ], poll: false
        commitShort = sh(script: 'git rev-parse HEAD', returnStdout: true).trim().substring(0, 7)
        echo "git commit: ${commitShort}"
    }

    sh "ls -la ./deployments/jenkins/"
    def ws = pwd()
    def common = load "${ws}/deployments/jenkins/common.groovy"
    //def common = load "./../../../../deployments/jenkins/common.groovy"
    echo common.helmTag

    def commonSubst = [
        _APP_TAG: appTag,
    ]

    stage("Build image hello-front ${appTag}") {
        googleCloudBuild  \
        credentialsId: common.gcloudCredentialsId,
            source: local('.'),
            request: file('front/deployments/cloudbuild/build-image.yaml'),
            substitutions: commonSubst + []
    }

    /* stage("Deploy ${appTag}") {
        googleCloudBuild  \
            credentialsId: common.gcloudCredentialsId,
            source: local('.'),
            request: file('deployments/cloudbuild/front/deployment.yaml'),
            substitutions: commonSubst + [
                _APP_NAME: "hello-api",
                _NAMESPACE   : common.namespace,
                _CLUSTER_ZONE: common.clusterZone,
                _CLUSTER_NAME: common.clusterName,
                _HELM_TAG    : common.helmTag,
                _ENVIRONMENT : common.environment,
            ]
    } */
}
