steps:
  - id: GenerateProtobuf
    name: 'gcr.io/$PROJECT_ID/protoc:latest'
    entrypoint: 'bash'
    args: [ './scripts/generate_proto.sh' ]

  - id: ImageBuildAndTag
    name: gcr.io/cloud-builders/docker
    args: [
      'build',
      '-f', './docker/prod/Dockerfile',
      '--target', 'release',
      '-t', 'gcr.io/${PROJECT_ID}/${_APP_NAME}:${_APP_TAG}',
      '-t', 'gcr.io/${PROJECT_ID}/${_APP_NAME}:latest',
      '.']

  - id: DeleteTAG
    name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container images delete gcr.io/${PROJECT_ID}/${_APP_NAME}:${_APP_TAG} --force-delete-tags --quiet || exit 0

  - id: ImagePushTAG
    name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/${PROJECT_ID}/${_APP_NAME}:${_APP_TAG}']

  - id: ImagePushLatestTAG
    name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/${PROJECT_ID}/${_APP_NAME}:latest']
