apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Values.app.deployment.name }}'
  labels:
    app: '{{ .Chart.Name }}'
    component: '{{ .Values.app.deployment.name }}'
spec:
  replicas: {{ .Values.app.deployment.hpa.minReplicaCount }}
  selector:
    matchLabels:
      app: '{{ .Chart.Name }}'
      component: '{{ .Values.app.deployment.name }}'
  template:
    metadata:
      labels:
        app: '{{ .Chart.Name }}'
        component: '{{ .Values.app.deployment.name }}'
      namespace: {{ .Values.gcp.namespace }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.app.deployment.image }}
          imagePullPolicy: {{ .Values.app.deployment.pullPolicy }}
          ports:
          - containerPort: {{ .Values.app.deployment.port.http }}
            name: http
            #protocol: TCP
          env:
            - name: PORT
              value: "8080"
            - name: OTHER_VARR
              value: "test"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/volumes/secrets/sa/credentials.json"
            - name: COPY_ENV_VAR_1
              valueFrom:
                configMapKeyRef:
                  key: ENV_VAR_1
                  name: configmap-env
          envFrom:
            - configMapRef:
                name: configmap-env
          volumeMounts:
            - name: volume-empty-dir
              mountPath: /volumes/empty-dir
            - name: volume-configmap-file
              mountPath: /volumes/config-map
            - name: volume-secrets-fake-credentials
              mountPath: /volumes/secrets/fake-credentials
            - name: volume-secrets-sa
              mountPath: /volumes/secrets/sa

      volumes:
        - name: volume-empty-dir
          emptyDir: {}
        - name: volume-configmap-file
          configMap:
            name: configmap-files
        - name: volume-secrets-fake-credentials
          secret:
            secretName: {{ .Chart.Name }}-fake-credentials
        - name: volume-secrets-sa
          secret:
            secretName: sa-hello-api-credentials
