apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Values.svc2.deployment.name }}'
  labels:
    app: '{{ .Values.svc2.name }}'
    component: '{{ .Values.svc2.deployment.name }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: '{{ .Values.svc2.name }}'
      component: '{{ .Values.svc2.deployment.name }}'
  template:
    metadata:
      {{- if .Values.useSvcMesh }}
      annotations:
        sidecar.istio.io/inject: '{{ .Values.svc2.deployment.injectAsmSideCar }}'
      {{- end }}
      labels:
        app: '{{ .Values.svc2.name }}'
        component: '{{ .Values.svc2.deployment.name }}'
      namespace: {{ .Values.gcp.namespace }}
    spec:
      containers:
        - name: {{ .Values.svc2.name }}
          image: {{ .Values.svc2.app.image }}
          imagePullPolicy: {{ .Values.svc2.app.pullPolicy }}
          ports:
          - containerPort: {{ .Values.svc2.app.grpcPort }}
            name: grpc-port
          command: ['/hello-svc', '-name=svc2', '-mode=grpc', '-grpc-port={{ .Values.svc2.app.grpcPort }}', '-http-port={{ .Values.svc2.app.port }}']
          env:
          - name: APP_ENV
            value: "{{ .Values.environment }}"
          #livenessProbe:
          #  httpGet:
          #    path: /healthz
          #    port: {{ .Values.svc2.app.port }}
          #    scheme: HTTP
          #  initialDelaySeconds: 15
          #  periodSeconds: 5
          #readinessProbe:
          #  httpGet:
          #    path: /healthz
          #    port: {{ .Values.svc2.app.port }}
          #    scheme: HTTP
          #  initialDelaySeconds: 15
          #  periodSeconds: 5
