apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.api.service.name }}'
  labels:
    app: '{{ .Chart.Name }}'
    component: '{{ .Values.api.service.name }}'
  namespace: '{{ .Values.gcp.namespace }}'
spec:
  selector:
    app: '{{ .Chart.Name }}'
    component: '{{ .Values.api.deployment.name }}'
  type: LoadBalancer
  ports:
    - port: {{ .Values.api.service.port.http }}
      targetPort: {{ .Values.api.deployment.port.http }}
