apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.app.service.name }}'
  labels:
    component: '{{ .Values.app.service.name }}'
  namespace: '{{ .Values.gcp.namespace }}'
spec:
  selector:
    app: '{{  .Values.app.deployment.name }}'
  type: '{{ .Values.app.service.type }}'
  #loadBalancerIP: '{{ .Values.app.service.loadBalancerIP }}'
  clusterIP: '{{ .Values.app.service.clusterIP }}' ## required with helm v3.2.x
  ports:
    - name: http
      port: {{ .Values.app.service.port.http }}
      targetPort: {{ .Values.app.deployment.port.http }}
      protocol: TCP
