steps:
  - name: gcr.io/cloud-builders/docker
    id: ImageBuildAndTag
    args: [
      'build',
      '-f', './docker/prod/Dockerfile',
      '--target', 'hello_api_release',
      '-t', 'gcr.io/${PROJECT_ID}/${_APP_NAME}:${_APP_TAG}',
      '.']

  - name: gcr.io/cloud-builders/docker
    id: ImagePushTAG
    args: ['push', 'gcr.io/${PROJECT_ID}/${_APP_NAME}:${_APP_TAG}']
