steps:
  - name: 'gcr.io/$PROJECT_ID/helm:${_HELM_TAG}'
    id: HelmUpgrade
    args: ['upgrade',
      '${_APP_NAME}', 'deployments/helm/hello', '--install','--force', '--reset-values',
      '--namespace', '$_NAMESPACE',
      '-f', './deployments/helm/hello/values.yaml',
      '-f', './deployments/helm/hello/values-development.yaml',
      '--set-string', 'app.deployment.image=gcr.io/${PROJECT_ID}/${_APP_NAME}:${_COMMIT_SHORT}']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_CLUSTER_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
      # for helm3 does not set the repo by default
      - 'HELM_REPO_NAME=stable'
      - 'HELM_REPO_URL=https://kubernetes-charts.storage.googleapis.com'
