version: '3.9'

services:
  # main container running npm run dev
  hello-front-vue:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
      target: vue_base
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]
    ports:
      - '4000:3000'
    environment:
      PORT: 3000
      HOST: 0.0.0.0
    volumes:
      - .:/app/front-vue
    networks:
      - hello

  # container to generate protobuf files
  protoc:
      build:
          context: .
          dockerfile: ./docker/protoc/Dockerfile
          target: release_dev
      entrypoint: ["tail"]
      command: ["-f", "/dev/null"]
      volumes:
          - .:/app/front-vue
          - ./../api:/app/api:ro
          - ./../third_party:/app/third_party:ro
      networks:
          - hello

networks:
  hello:
    name: hello
    external: true
