version: '3.9'

services:
  # main container running npm run dev
  hello-front-vue:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
      target: vue_base
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]
    ports:
      - '4000:3000'
    environment:
      PORT: 3000
      HOST: 0.0.0.0
    volumes:
      - .:/app/front-vue
    networks:
      - hello

networks:
  hello:
    name: hello
    external: true
