
environment: staging

# GCP
gcp:
  projectId: samyn-project4
  namespace: lazone

useSvcMesh: true

api:
  name: hello-api
  # deployment
  deployment:
    name: "hello-api-deploy"
    grpcPort: 7080
    port: 8080
    image:
    pullPolicy: Always
    injectAsmSideCar: 'true'
    hpa:
      name: 'hello-api-deploy-hpa'
      minReplicaCount: 1
      maxReplicaCount: 1
      targetCPUUtilizationPercentage: 80

  esp:
    useEsp: true
    useHttps: true
    debug: true
    host: "hello-api.endpoints.samyn-project4.cloud.goog"
    port: 9000

svc1:
  name: hello-svc1
  deployment:
    name: "hello-svc1-deploy"
    grpcPort: 7081
    port: 8081
    image:
    pullPolicy: Always
    injectAsmSideCar: 'true'

svc2:
  name: hello-svc2
  deployment:
    name: "hello-svc2-deploy"
    grpcPort: 7082
    port: 8082
    image:
    pullPolicy: Always
    injectAsmSideCar: 'true'
