
environment: staging

gcp:
  projectId: samyn-project4
  namespace: lazone

useSvcMesh: false

api:
  name: hello-api
  deployment:
    name: "hello-api-deploy"
    injectAsmSideCar: 'false'

  app:
    grpcPort: 7080
    port: 8080
    image:
    pullPolicy: Always
    cpu:
      min: 20m
      max: 60m
    memory:
      min: 64Mi
      max: 90Mi

  esp:
    useEsp: true
    useHttps: true
    debug: false
    host: "hello-api.endpoints.samyn-project4.cloud.goog"
    port: 9000
    cpu:
      min: 30m
      max: 70m
    memory:
      min: 64Mi
      max: 90Mi

  hpa:
    name: 'hello-api-deploy-hpa'
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 70

svc1:
  name: hello-svc1
  deployment:
    name: "hello-svc1-deploy"
    injectAsmSideCar: 'false'
  app:
    grpcPort: 7081
    port: 8081
    image:
    pullPolicy: Always
    cpu:
      min: 15m
      max: 40m
    memory:
      min: 25Mi
      max: 44Mi

svc2:
  name: hello-svc2
  deployment:
    name: "hello-svc2-deploy"
    injectAsmSideCar: 'false'
  app:
    grpcPort: 7082
    port: 8082
    image:
    pullPolicy: Always
    cpu:
      min: 15m
      max: 40m
    memory:
      min: 25Mi
      max: 44Mi