
environment: staging

gcp:
  projectId: samyn-project4
  namespace: lazone

useSvcMesh: false

api:
  name: hello-api
  deployment:
    name: "hello-api-deploy"
    injectAsmSideCar: 'false'

  app:
    grpcPort: 7080
    port: 8080
    image:
    pullPolicy: Always
    cpu:
      min: 50m
      max: 100m
    memory:
      min: 64Mi
      max: 100Mi

  hpa:
    name: 'hello-api-deploy-hpa'
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 70

  esp:
    useEsp: true
    useHttps: true
    debug: false
    host: "hello-api.endpoints.samyn-project4.cloud.goog"
    port: 9000
    cpu:
      min: 80m
      max: 160m
    memory:
      min: 64Mi
      max: 100Mi

svc1:
  name: hello-svc1
  deployment:
    name: "hello-svc1-deploy"
    injectAsmSideCar: 'false'
  app:
    grpcPort: 7081
    port: 8081
    image:
    pullPolicy: Always

svc2:
  name: hello-svc2
  deployment:
    name: "hello-svc2-deploy"
    injectAsmSideCar: 'false'
  app:
    grpcPort: 7082
    port: 8082
    image:
    pullPolicy: Always
