
environment: staging

# GCP
gcp:
  projectId: samyn-project4
  namespace: lazone

api:
  name: hello-api
  # deployment
  deployment:
    name: "hello-api-deploy"
    port: 8080
    image:
    pullPolicy: Always
    hpa:
      name: 'hello-api-deploy-hpa'
      minReplicaCount: 1
      maxReplicaCount: 1
      targetCPUUtilizationPercentage: 80

  esp:
    useHttps: false
    debug: false
    host: "hello-api.endpoints.samyn-project4.cloud.goog"
    port: 9000

svc1:
  name: hello-svc1
  deployment:
    name: "hello-svc1-deploy"
    port: 8081
    image:
    pullPolicy: Always
