type: google.api.Service
config_version: 3

name: hello-api.endpoints.samyn-project4.cloud.goog

title: Hello gRPC API
apis:
  - name: hello.endpoints.health.Health
  - name: hello.endpoints.notify.Notify
  #- name: hello.endpoints.health.Ping

usage:
  rules:
    - selector: hello.endpoints.health.Health.*
      allow_unregistered_calls: true
