type: google.api.Service
config_version: 3

name: hello-api.endpoints.samyn-project4.cloud.goog

title: Hello gRPC API
apis:
  - name: hello.endpoints.health.Health
  - name: hello.endpoints.notify.Notify
  - name: hello.endpoints.sandbox.Sandbox
  #- name: hello.endpoints.health.Ping

usage:
  rules:
    - selector: "*"
      allow_unregistered_calls: false
    - selector: hello.endpoints.health.Health.Status
      allow_unregistered_calls: true
    - selector: hello.endpoints.health.Health.Healthz
      allow_unregistered_calls: true
    - selector: hello.endpoints.sandbox.Sandbox.*
      allow_unregistered_calls: true
