steps:
  - id: 'Decrypt github private key'
    name: 'gcr.io/cloud-builders/gcloud'
    args:
        - 'kms'
        - 'decrypt'
        - '--location=${_GCP_REGION}'
        - '--keyring=${_KMS_KEYRING_NAME}'
        - '--key=${_KMS_KEY_NAME}'
        - '--ciphertext-file=${_GITHUB_PRIVATE_KEY_ENCRYPTED_PATH}'
        - '--plaintext-file=/root/.ssh/${_GITHUB_PRIVATE_KEY_DECRYPTED_FILE}'
    volumes:
      - name: 'ssh'
        path: '/root/.ssh'

  - id: 'Setup github private key'
    name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod 400 /root/.ssh/${_GITHUB_PRIVATE_KEY_DECRYPTED_FILE}
        cat <<EOF >/root/.ssh/config
        Hostname github.com
        IdentityFile /root/.ssh/${_GITHUB_PRIVATE_KEY_DECRYPTED_FILE}
        EOF
        ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
    volumes:
      - name: 'ssh'
        path: '/root/.ssh'

  - id: 'Config git with ssh mode'
    name: 'gcr.io/cloud-builders/git'
    entrypoint: 'git'
    args:
      - 'config'
      - '--global'
      - '--add'
      - 'url.git@github.com:.insteadOf'
      - 'https://github.com/'
    volumes:
      - name: 'ssh'
        path: '/root/.ssh'

  - id: 'go mod init'
    name: golang:1.16
    args: ['go', 'mod', 'init', '${_FUNCTION_GO_MODULE}']
    dir: '${_FUNCTION_SOURCE_PATH}'

  - id: 'Generate Protobuf'
    name: 'gcr.io/$PROJECT_ID/protoc:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "generate protobuf in ./pkg/protobuf/"
        ./scripts/generate_proto.sh
        echo "copy ./pkg/protobuf to ./${_FUNCTION_SOURCE_PATH}/"
        cp -r ./pkg/protobuf "./${_FUNCTION_SOURCE_PATH}/"
        echo "add go.mod replace directive"
        echo "replace github.com/dev2choiz/hello/pkg/protobuf => ./protobuf" >> "./${_FUNCTION_SOURCE_PATH}/go.mod"

  - id: 'create go.mod in ./protobuf'
    name: golang:1.16
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd "./${_FUNCTION_SOURCE_PATH}/protobuf"
        go mod init github.com/dev2choiz/hello/pkg/protobuf

  - id: 'Debug 2'
    name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        ls -la /root/.ssh
        cat /root/.ssh/config
        cat go.mod
    volumes:
      - name: 'ssh'
        path: '/root/.ssh'
    dir: '${_FUNCTION_SOURCE_PATH}'

  - id: 'go get github.com/dev2choiz/hello@xxxxxx'
    name: golang:1.16
    args: ['go', 'get', 'github.com/dev2choiz/hello@${_APP_TAG}']
    env: ['GOPRIVATE=${_GITHUB_REPOSITORY}']
    dir: '${_FUNCTION_SOURCE_PATH}'
    volumes:
      - name: "ssh"
        path: "/root/.ssh"

  - id: 'go mod tidy'
    name: golang:1.16
    args: ['go', 'mod', 'tidy']
    dir: '${_FUNCTION_SOURCE_PATH}'
    volumes:
      - name: "ssh"
        path: "/root/.ssh"

  - id: 'go mod vendor'
    name: golang:1.16
    args: ['go', 'mod', 'vendor']
    dir: '${_FUNCTION_SOURCE_PATH}'
    volumes:
      - name: "ssh"
        path: "/root/.ssh"

  - id: 'Deploy cloud function'
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', '${_FUNCTION_NAME}',
       '--source', '.',
       '--runtime', 'go116',
       '--region', '${_GCP_REGION}',
       '--entry-point', '${_ENTRYPOINT}',
       '--trigger-topic', '${_TRIGGER_TOPIC}',
       '--timeout', '30s',
       '--service-account', '${_SERVICE_ACCOUNT}',
       '--set-env-vars', 'APP_ENV=${_APP_ENV}',
       #'--clear-vpc-connector'
       ]
    dir: '${_FUNCTION_SOURCE_PATH}'
