// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/dev2choiz/hello/pkg/logger"
)

// Injectors from wire.go:

func InitializeLogger() logger.LoggerInterface {
	loggerInterface := logger.NewLogger()
	return loggerInterface
}
