#!groovy

parameters([
    string(name: 'VERSION', defaultValue: 'dev', description: 'branch or tag', trim: true),
    string(name: 'ENVIRONMENT', defaultValue: 'staging', description: 'environment', trim: true),
])

node {
    def repoURL             = 'git@github.com:dev2choiz/hello.git'
    def environment         = params.ENVIRONMENT
    def appTag              = params.VERSION
    def migrationType       = params.MIGRATION_TYPE
    def commitShort         = ""

    echo "start building tag/branch '${appTag}'. env: ${environment}"
    checkout scm: [
        $class: 'GitSCM',
        userRemoteConfigs: [[url: repoURL]],
        branches: [[name: appTag]]
    ], poll: false

    def ws = pwd()
    def modCloudFunc = load "${ws}/deployments/jenkins/modules/cloudFunc.groovy"
    stage('Deploy hello-pg-migration') {
        modCloudFunc.deployPgMigration(appTag, environment)
    }
}
