#!groovy

parameters([
    string(name: 'VERSION', defaultValue: 'dev', description: 'branch or tag', trim: true),
])

node {
    def repoURL = 'git@github.com:dev2choiz/hello.git'
    def helmTag = '3.2.4'
    def projectName = 'hello-api'
    def projectId = "samyn-project4"
    def gcloudCredentialsId = projectId
    def clusterZone = "europe-west1-d"
    def clusterName = "samyn-cluster"
    def namespace   = "lazone"
    def environment = "staging"
    def appTag      = params.VERSION
    def commitShort = ""

    echo "start building tag/branch '${appTag}'"
    checkout scm: [
        $class           : 'GitSCM',
        userRemoteConfigs: [[url: repoURL]],
        branches         : [[name: appTag]]
    ], poll: false
    commitShort = sh(script: 'git rev-parse HEAD', returnStdout: true).trim().substring(0, 7)
    echo "git commit: ${commitShort}"

    def cbSubstitutions = [
        _APP_NAME:     projectName,
        _APP_TAG:      appTag,
    ]

    echo "build docker image tag: ${appTag}"
    stage('Build image') {
        googleCloudBuild  \
        credentialsId: gcloudCredentialsId,
            source: local('.'),
            request: file('deployments/cloudbuild/build-image.yaml'),
            substitutions: cbSubstitutions + []
    }
    echo "deploy docker image tag: ${appTag}"
    stage('Deployment') {
        googleCloudBuild  \
            credentialsId: gcloudCredentialsId,
            source: local('.'),
            request: file('deployments/cloudbuild/deployment.yaml'),
            substitutions: cbSubstitutions + [
                _NAMESPACE   : namespace,
                _CLUSTER_ZONE: clusterZone,
                _CLUSTER_NAME: clusterName,
                _HELM_TAG    : helmTag,
                _ENVIRONMENT : environment,
            ]
    }
}
