#!groovy

parameters([
    string(name: 'VERSION', defaultValue: 'dev', description: 'branch or tag', trim: true),
])

node {
    def repoURL = 'git@github.com:dev2choiz/hello.git'
    def projectName = 'hello-api'
    def environment = "staging"
    def appTag      = params.VERSION
    def commitShort = ""

    echo "start building tag/branch '${appTag}'"
    stage("Checkout ${appTag}") {
        checkout scm: [
            $class           : 'GitSCM',
            userRemoteConfigs: [[url: repoURL]],
            branches         : [[name: appTag]]
        ], poll: false
        commitShort = sh(script: 'git rev-parse HEAD', returnStdout: true).trim().substring(0, 7)
        echo "git commit: ${commitShort}"
    }

    def ws = pwd()
    def common = load "${ws}/deployments/jenkins/common.groovy"

    def commonSubst = [
        _APP_TAG: appTag,
        _APP_NAME: "hello-api",
    ]

    stage("Build image hello-api ${appTag}") {
        googleCloudBuild  \
        credentialsId: common.gcloudCredentialsId,
            source: local('.'),
            request: file('deployments/cloudbuild/apis/build-image/cloudbuild.yaml'),
            substitutions: commonSubst + []
    }

    stage("Deploy ${appTag}") {
        googleCloudBuild  \
            credentialsId: common.gcloudCredentialsId,
            source: local('.'),
            request: file('deployments/cloudbuild/apis/deployment/cloudbuild.yaml'),
            substitutions: commonSubst + [
                _NAMESPACE   : common.namespace,
                _CLUSTER_ZONE: common.clusterZone,
                _CLUSTER_NAME: common.clusterName,
                _HELM_TAG    : common.helmTag,
                _ENVIRONMENT : environment,
            ]
    }
}
